---
title: "Model-Based Deep Neural Network to Enhance MPC and MPPI Controller in Dynamics Environment"
subtitle: "Institute of Technology of Cambodia"
author: "DIN Sokheng"
date: "28-June-2024"
output:
  xaringan::moon_reader:
    css: ["default", "style.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "https://platform.twitter.com/widgets.js"
    seal: false
    includes:
      in_header: "toc.html"
---

class: center, middle, title-slide

# Model-Based Deep Neural Network to Enhance MPC and MPPI Controller in Dynamics Environment

.department[Department of Electrical and Energy Engineering]

.advisor[SENG Theara]
.author[DIN Sokheng]
.date[28-June-2024]

---

# Table of Contents
.toc[]


---
# Introduction
Recently, Artificial Intelligence(AI) has gained momentum in the daily basis usage in real-world application with Robotics being one of the primary areas of focus when we talk about Artificial Intelligence. Deep Neural Networks(DNNs) are particularly efficient with in solving data-driven problems. They work by processing a diverse stream of data and fitting it into an optimization problem to uncover hidden patterns within the data. 
---
## Study Background
In Robotics, a common challenge is dealing with the uncertainty of mathematical methods, especially in unknown, real-time environments . This uncertainty can compromise even the most advanced control algorithms that rely solely on the original system model, rather than the actual model encountered in practice. To address this issue,  mainly recent innovations involve integrating DNNs to discover a hidden parameter of model trained based on real-world data. This model is then combined with the original system to significantly enhance accuracy in complex and dynamics environments.

---
## Objective Of Work
The primary objective of this work is to enhance the accuracy of Model Predictive Control (MPC) algorithms and Model Predictive Path Integral (MPPI) in environments with unknown parameters and dynamic obstacles. This will be achieved by implementing deep learning techniques. The MPC will utilize the Acados library to solve the Nonlinear Optimization Problem (NLP), while the MPPI will be based on the methodologies described in the original paper \cite{williams2017information}. The PyBullet will be used as a simulation environment by setting the friction, gravitational force and dynamics response from the differential drive robot that defined in the URDF format.

## Scope of Study
## Thesis Outline

---
# Design Methodology
## Model Predictie Control
## Model Predictive Path Integral
## Path Constraint Obstacle Avoidance
## Deep Neural Network
## Model-Based Deep Neural Network
---

# Result and Discussion
## System Model
## System Identification using each Controller PyBullet Environment
### Design Deep Neural Network
## Model Predictive Control with Learned Dyanmcis using Acados
### Training the Neural Network
### Compare MPC performance nominal model vs learned model
## Model Predictive Path Integral Control using PyTorch
### Training the Neural Network
### Compare MPPI performance nominal model vs learned model
---

# Conclusion and Future Work
